### PR TITLE
add mocha hooks

### PR DESCRIPTION
**Pull request by stephanebachelier**
add support for `after`, `afterEach`, `before`, `beforeEach`.

### CODE REVIEW

**Comment by extrabacon** [comment]
Will be published in the next version.

**Comment by stephanebachelier** [comment]
@extrabacon cool :)

**Comment by extrabacon** [comment]
Sorry for the delay... published in 1.1.4.

**Comment by jwhitmarsh** [comment]
`afe` is taking precedence over `af`, presumably because `bdd.cson` is loaded before `functions.cson`. Is there anything that can be done about that?

**Pull request merged**
