### PR TITLE
Add snippets to TypeScript files

### PR DESCRIPTION
**Pull request by markogresak**
I have copied all of the snippets and changed grammar, I couldn't find
a better (more reusable) solution.

Questions/TODO:

 - [ ] Add a setting checkbox to confirm applying TypeScript snippets - I'm not sure how this can be done.

### CODE REVIEW

**Comment by extrabacon** [comment]
Sorry for the delay, just got back from vacation.

This looks good, but having duplicate snippets for the TypeScript syntax will make evolution and maintenance more complex. I will probably need your help to update the TS snippets in the future.

**Comment by markogresak** [comment]
No problem, welcome back! Glad you like it.
What about the checkbox, is this even doable, or do we skip this altogether? 

For duplicating, I've used a primitive bash script:

``` bash
for file in *.cson; do echo -e "\n$(sed -e 's/\.source\.js/\.source\.ts/g' $file)" >> $file; done
```

When looking at this script again, I noticed that I've screwed up. Echoing the file contents will make `\t` characters an actual tab in script, not the character. 
But I have to fix the script to make it more usable for continuous development and I will fix this too.
My idea is to have a bash script and stick it into `script` section in the `package.json`, then anyone (on machine supporting bash) could run the script with `npm run [something]` and have the snippets regenerated. If you agree, do you have any ideas how to name the script? :smile:

**Comment by extrabacon** [comment]
I would not worry about that. I would prefer to have real TypeScript-optimized snippets (even if it means more effort) than duplicates.

**Comment by markogresak** [comment]
I have now amended the last commit to fix my mistake. I have used this shell script and it can be used for as long as JavaScript and TypeScript version do not diverge. 

If there will be some case where TypeScript version can be improved, I will be happy to help and manage the TypeScript part of snippets. The script is there just to make things go faster.

I doubt there is a a lot to optimize. TypeScript uses standard ES2015 syntax, the only thing that one could add is `[variable name/function]:[type]`, but this format is often times not necessary because TypeScript's type inference. Writing types is more like writing a variable name, the snippet can't help a lot in these cases.

After creating (copying) TypeScript part of snippets, I added them snippets to atom to test my TypeScript workflow and I haven't noticed anything that would bother me. In my opinion, having a snippet always prompt you to write variable type or function return type could turn out to be annoying for some people. 

``` bash
for file in *.cson; do 
  if [[ "$file" != 'json.cson' ]]; then
    js=$((head -n $(($(grep -nm 1 '.source.ts' $file | cut -d: -f1) - 2)) $file 2>/dev/null || cat $file) | sed -e 's/\\/\\\\/g')
    echo -e "$js\n\n$( sed -e 's/\.source\.js/\.source\.ts/g' <<< $js)" > $file
  fi
done
```

The script assumes that the file will be either without `.source.ts` or there will be an empty newline before (can change easily).
I have formatted the script to be better readable, but this can still be used as one-line script in package.json. If you're interested, I can explain what's going on here.

**Comment by tjoskar** [comment]
Hi,

I just created a fork of this project and replaced all `.source.js` with `.source.js, .source.ts` and it seems to works fine in both `ts` and `js` files (we don't need to duplicate all snippets with this approach)

You can see my changes here: https://github.com/extrabacon/atom-turbo-javascript/compare/master...tjoskar:feature/typescript-support

**Comment by tjoskar** [comment]
I created a pull request for simplicity #27

**Comment by markogresak** [comment]
Closing in favour of #27.

**Pull request closed without merging**
