### PR TITLE
Adding typescript support

### PR DESCRIPTION
**Pull request by tjoskar**
Adding `ts`-source extension in all snippets to also support typescripts.

Fixing #17.
Possible duplicate of #18.

### CODE REVIEW

**Comment by markogresak** [comment]
I have tried that when creating #18, but it didn't seem to work then. If you are sure it works, this is much better than what I did, especially for keeping both versions the same.

As for @extrabacon's comment:
> I would not worry about that. I would prefer to have real TypeScript-optimized snippets (even if it means more effort) than duplicates.

I still stand at what I have responded with then, current .js snippets should work just fine in .ts and there is no special snippets I could think of. 

Btw, you should also check if the snippets work in .tsx files (added in TypeScript 1.6).

**Comment by tjoskar** [comment]
Alright, that explains your solution.
I have been using this package all day today and it works fine in both .ts and .js (after my changes). You can try it for yourself, just to confirm that it works. I'm using the latest, stable, version of Atom `v1.0.19`. 

I saw @extrabacon comment and I agree with [https://github.com/extrabacon/atom-turbo-javascript/pull/18#issuecomment-131859920](you). Typescript is a superset of javascript so all javascript snippets should work just fine in typescript. We could of course add Typescript-oriented snippets (like `enum` and `interface`) but that is a different story. I would say that the first step is to make the current snippets working in both `js` and `ts` files.

Regarding `tsx`; I am not using `tsx` in my daily workflow but I can of course create a `tsx` file and try it out. I will do that tomorrow and get back to you.

**Comment by tjoskar** [comment]
@markogresak, if one add `.source.tsx` to the list (eg. `.source.js, .source.ts, .source.tsx`), the snippets works in `tsx`-files as well.

**Comment by markogresak** [comment]
That's awesome, thanks for testing and adding it.

**Comment by dsifford** [comment]
Status? This is sorely needed! (ps: nice work @tjoskar & @markogresak :smile: )

**Comment by markogresak** [comment]
@dsifford I'm not sure, nor @extrabacon or any of the contributors (not sure if there are any) responded after the two responses in #18. You could probably checkout this PR and use it instead of current release. I believe [this discussion](https://discuss.atom.io/t/load-developing-package/2554/11) should help if you wish to try this.

**Comment by dsifford** [comment]
@markogresak That's a shame. I went and applied the changes from this PR shortly after making my first comment. Pretty easy fix, but I'll have to do it across my different machines unless this gets pulled in. \*sigh\*, oh well...

**Comment by extrabacon** [comment]
I'm sorry, I never got to this PR because I could not easily test it (I have no experience with Typescript). But thanks to your feedback, I will give it a try today and go for a quick merge.

**Comment by extrabacon** [comment]
Those changes were merged and published into 1.3.0. Let me know of any adjustment that need to be made as I did not test Typescript integration properly.

**Comment by dsifford** [comment]
And @extrabacon delivers! Awesome. Thanks man, everything is working great.

**Pull request merged**
